#! /usr/bin/env python
# -*- coding: utf-8 -*-

from snakemake.utils import min_version

min_version("6.4.1")

from snakemake.exceptions import RuleException


wildcard_constraints:
    caseid = 'TCGA-[0-9A-Z]{2}-[0-9A-Z]{4}',
    sampid = 'TCGA-[0-9A-Z]{2}-[0-9A-Z]{4}-\d{2}[A-Z]',
    uuid = '[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-4[0-9A-Fa-f]{3}-[89ABab][0-9A-Fa-f]{3}-[0-9A-Fa-f]{12}'



# The main entry point of your workflow.
# After configuring, running snakemake -n in a clone of this repository should successfully execute a dry-run of the workflow.


report: "report/workflow.rst"

# Allow users to fix the underlying OS via singularity.
singularity: "docker://continuumio/miniconda3"


rule all:
    input:
        # The first rule should define the default target files
        # Subsequent target rules can be specified below. They should start with all_*.


include: "rules/common.smk"
include: "rules/other.smk"
